package com.gtreb.cleopattesmanager

import dev.icerock.moko.resources.StringResource

// This file will be generated by moko-resources plugin
// It will contain all the string resources from strings.xml 